Numpy:

Why Numpy is Faster than Python Lists:

1.Continous Memory (Compact Storage)

In [1]:
import numpy as np

In [5]:
py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])

print("Python list elements addresses:")
for x in py_list:
    print(id(x))

print("\nNumpy array element addresses:")
print(np_array.__array_interface__["data"])

Python list elements addresses:
140718042821544
140718042821576
140718042821608
140718042821640
140718042821672

Numpy array element addresses:
(2540208397744, False)


2.Vectorization(No Loops in Py* )

In [7]:
#Python list with normal for loop:
list_data = [1,2,3,4,5]
list_result = []
for x in list_data:
    list_result.append(x * 2)
print("List result:",list_result)

#Numpy array (vectorized)
np_data = np.array([1,2,3,4,5])
np_result = np_data * 2
print("Numpy result:",np_result)

List result: [2, 4, 6, 8, 10]
Numpy result: [ 2  4  6  8 10]


3.Same Data Type (Homogeneous Data):

In [8]:
py_list = [1,'2',3.5,4,True]
np_array = np.array([1,2,3,4])

types_list = []
for x in py_list:
    types_list.append(type(x))
print("Python list types:",types_list)
print("Numpy array type:",np_array.dtype)

Python list types: [<class 'int'>, <class 'str'>, <class 'float'>, <class 'int'>, <class 'bool'>]
Numpy array type: int64


What happens if we put mixed data types in a Numpy array:


In [9]:
#Example 1---> int + str
arr = np.array([1,2,"hello",3])
print(arr)
print("Array dtype:",arr.dtype)
# The Integers (1,2,3) were converted into strings ('1','2','3')
# Numpy decided the final type should be strings because a string can represent be
# <u11 means "unicode string of maximum length 21".

['1' '2' 'hello' '3']
Array dtype: <U21


In [11]:
# Example 2 --> float + int
arr = np.array([1,2,3.5,4])
print(arr)
print("Array:",arr)
print("Array dtype:",arr.dtype)

# The integers [1,2,4] were converted into floats [1.0,2.0,4.0]
# Numpy chose float64 because floats can hold decimals values,and they can also hi

[1.  2.  3.5 4. ]
Array: [1.  2.  3.5 4. ]
Array dtype: float64


In [14]:
#Example 3 ---> int + bool
arr = np.array([1,0,True,False])
print(arr)
print("Array:",arr)
print("Array dtype:",arr.dtype)

# True was converted to 1, and False was converted to 0
# Numpy chose int64,since integers can reprsent both numbers and booleans.

[1 0 1 0]
Array: [1 0 1 0]
Array dtype: int64


1.Creating Numpy Array:

In [21]:
import numpy as np

In [22]:
#Creating numpy array:
arr1 = np.array([1,2,3,4,5]) # convert list to numpy array

#vector
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [24]:
#Creating 2D array
arr2 = np.array([[1,2,3],[4,5,6]])

#matrics
print(arr2)


[[1 2 3]
 [4 5 6]]


In [25]:
# creating array of zeros:
arr3 = np.zeros((2,3)) #(2,3) --> 2 rows , 3 columns
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
#creating arrays of ones
arr4 = np.ones((3,4)) # (3,4) -===> 3 rows , 4 columns
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
#creating identitiy matrics:
arr5 = np.identity((4)) 
print(arr5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#creating array using arange
# arange __> counter of range function of python
arr6 = np.arange(11)
print(arr6)
print(type(arr6))

[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [36]:
#creating array using arange
arr7 = np.arange(10,25)
print(arr7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [37]:
#creating array using arange
arr7 = np.arange(10,25,2)
print(arr7)

[10 12 14 16 18 20 22 24]


In [38]:
#creating array using inspace ---> useto make equi-distance between the elemments
arr8 = np.linspace(0,20,10)
print(arr8)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [40]:
#creating array using copy
arr9 = arr8.copy()
print(arr9)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


2.Numpy Array Properties & Attributes:


Shape:

In [41]:
# find Shape of array --> return the dimension of array (rows,columns)
print(arr1) # array has 5 elements is one dimension.
print(arr1.shape)
print(arr4)
print(arr4.shape)

[1 2 3 4 5]
(5,)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [44]:
#creating multidimenstional array space
arr10 = np.array([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])
print(arr10)
print(arr10.shape) #(2 rows , 2 columns ,2 matrices )


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


ndim:

In [47]:
# ndim --> return the dimension of numpy array
print(arr10)
print(arr10.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [46]:
print(arr5)
print(arr5.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2


size:

In [48]:
#size --->> rreturn number of items:
print(arr10)
print(arr10.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


itemsize:

In [49]:
#itemsize ---> return how umch memory each array elemnets uses in bytes./
print(arr10)
print(arr10.itemsize)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


astype

In [59]:
#astype --> use to convert the data types of array
print(arr10)
print(arr10.dtype)


print(arr10.astype("float"))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


List vs Numpy-Array:

. Less Memory

In [60]:
import sys

In [61]:
#Less Memory -->Numpy takes less memory than python list
py_list = list(range(1000))
np_array = np.arange(1000)

print("Python list size:", sys.getsizeof(py_list), "bytes")
print("Numpy array size:", np_array.nbytes, "bytes")


Python list size: 8056 bytes
Numpy array size: 8000 bytes


Faster:

In [62]:
import time

In [63]:
#Faster -->  Numopy array operational speed much faster than list operations
 # Python List
py_list = list(range(1_000_000))
start = time.time()
py_result = []
for x in py_list: # loop aperations
    py_result.append(x * 2)
end = time.time()
print("Python list time:", end - start , "seconds")

# Numpy array
np_array = np.arange(1_000_000)
start = time.time()
np_result = np_array * 2  # vectorized operations
end = time.time()
print("Numpy array time:", end - start , "seconds")

Python list time: 0.5195338726043701 seconds
Numpy array time: 0.006946086883544922 seconds


Convenient:

In [66]:
#Convenient ---> Numpy is simpler and cleaner , this makes numpy more convenient

# Adding two list elements by element using python operations/.
list1 = [1,2,3,4,5]
list2 = [10,20,30,40,50]

result_list = []
for i in range(len(list1)):  # need loop and indexing
    result_list.append(list1[i] + list2[i])

print("Python list addition:", result_list)

# Adding two lists elements by elements using numpy operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

result_array = arr1 + arr2  #direct operations
print("Numpy array addition:",result_array)

Python list addition: [11, 22, 33, 44, 55]
Numpy array addition: [11 22 33 44 55]


Indexing & Slicing in Numpy: 

In [73]:
#simple array
arr12 = np.arange(24)
print(arr12)

#indexing
print(arr12[7])
print(arr12[-1])

#slicing
print(arr12[7:14])
print(arr12[-6:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
7
23
[ 7  8  9 10 11 12 13]
[18 19 20 21 22]


In [91]:
#Multidimenstional matrics 
arr13 = np.arange(24).reshape(6,4) # reshape : converts the array into given matrics
print(arr13)

#indexing
print(arr13[2]) # return row

#slicing
print(arr13[2:5])  # return rows

#slicing rows & columns --> arr(slice rows , slice column)
print(arr13[:,2]) # return rows & column
print(arr13[:,1:4]) # return rows & columns
print(arr13[4:6,2:4]) # return rows & columns


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[ 8  9 10 11]
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 2  6 10 14 18 22]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]
 [21 22 23]]
[[18 19]
 [22 23]]


In [89]:
# multiblock & multidimenstional matrics:
arr14 = np.arange(32).reshape(2,4,4) #(block,row,cloumn)
print(arr14)

#indexing
print(arr14[0]) # first block
print(arr14[1]) # second block

print(arr14[0][0]) #first  bloxk first row

print(arr14[1][0]) # second block first row
 
print(arr14[0][0][1]) # first clock row 1 col 2 
print(arr14[1][0][1]) # second block row 1 col 2

#Slicing
print(arr14[:][0][0]) # All blocks ,first row , first col
print(arr14[:][1][1]) # All blocks ,second row, second col

print(arr14[0][:][:]) # Entire first block
print(arr14[1][:][:]) # Entire second block

print(arr14[:][:][0]) # All blocks,all rows
print(arr14[:][:][1]) # All blocks,all rows 


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[0 1 2 3]
[16 17 18 19]
1
17
[0 1 2 3]
[20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


Numpy Iteration:

In [92]:
for i in arr13:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [93]:
#print item wise
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [94]:
# print item wise in one block:
for i in np.nditer(arr14[0]):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


Numpy Operation:

In [96]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [97]:
#Addition:
print(arr1+arr2)

#subtraction:
print(arr1-arr2)

#Multip[lication:
print(arr1*arr2) #vector multiplication
print(arr1*2)    # scalar multi[lication

#Division:
print(arr1/arr2) #vector division
print(arr2/2)   #scalar division



[ 5  7  9 11 13 15]
[-3 -3 -3 -3 -3 -3]
[ 4 10 18 28 40 54]
[ 2  4  6  8 10 12]
[0.25       0.4        0.5        0.57142857 0.625      0.66666667]
[2.  2.5 3.  3.5 4.  4.5]


In [98]:
print(arr1>3)
print(arr1==arr2)

print(arr2>=5)


[False False False  True  True  True]
[False False False False False False]
[False  True  True  True  True  True]


In [2]:
import numpy as np
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [5]:
#dot Function
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [6]:
#Error ----> matrics order mismatch 
arr1.dot(arr3)

NameError: name 'arr1' is not defined

In [8]:
#max
print(arr3.max())
#row wise maximum 
print(arr3.max(axis=0))
#column wise maximum
print(arr3.max(axis=1))

#min
print(arr3.min())
#row wise minimum 
print(arr3.min(axis=0))
#column wise minimum
print(arr3.min(axis=1))


5
[3 4 5]
[2 5]
0
[0 1 2]
[0 3]


In [11]:
#sum
print(arr4.sum())
#row wise sum
print(arr4.sum(axis=0))
#column wise sum
print(arr4.sum(axis=1))

#mean
print(arr4.mean())
#row wise mean
print(arr4.mean(axis=0))
#column wise mean
print(arr4.mean(axis=1))

#median
print(np.median(arr4))
#row wise median
print(np.median(arr4,axis=0))
#column wise median
print(np.median(arr4,axis=1))


51
[24 27]
[13 17 21]
8.5
[8. 9.]
[ 6.5  8.5 10.5]
8.5
[8. 9.]
[ 6.5  8.5 10.5]


In [12]:
#square root
print(np.sqrt(arr4))

#exponent
print(np.exp(arr4))

#sin
print(np.sin(arr4))

#cos
print(np.cos(arr4))

[[2.44948974 2.64575131]
 [2.82842712 3.        ]
 [3.16227766 3.31662479]]
[[  403.42879349  1096.63315843]
 [ 2980.95798704  8103.08392758]
 [22026.46579481 59874.1417152 ]]
[[-0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849]
 [-0.54402111 -0.99999021]]
[[ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]
 [-0.83907153  0.0044257 ]]


Reshaping Numpy:

Ravel:

In [32]:
# ravel ---> convert the higher dimenstional array to one dimenstional array
arr10 = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print(arr10)
print(arr10.ravel())

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


Reshape:

In [37]:
#Reshape ----> Reshape the array , but in context of vector
# if 24 items ---> reshape = (1,24)(24,1)(6,4)(4,6)(12,2)(2,12)
arr5 = np.arange(24)
arr6 = arr5.reshape(2,12)
print(arr6)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [42]:
#transpose --->rows to columns & columns to rows
print(arr6.transpose())

[[ 0 12]
 [ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]]


Stack:

In [49]:
#stack ---> combine the two or more arrays(the arrays must be same shape )
print(arr3)
arr6 = np.arange(12,18).reshape(2,3)
print(arr6)
arr7 = np.arange(19,25).reshape(2,3)
print(arr7)

#horizantal stack
print(np.hstack((arr3,arr6,arr7)))

#vertical stack
print(np.vstack((arr3,arr6,arr7)))

[[0 1 2]
 [3 4 5]]
[[12 13 14]
 [15 16 17]]
[[19 20 21]
 [22 23 24]]
[[ 0  1  2 12 13 14 19 20 21]
 [ 3  4  5 15 16 17 22 23 24]]
[[ 0  1  2]
 [ 3  4  5]
 [12 13 14]
 [15 16 17]
 [19 20 21]
 [22 23 24]]


split:

In [57]:
#split ---> split the array into equal parts
print(arr3)

#horizantal split --> split the array in form of columns
print(np.hsplit(arr3,3))

#vertical split ---> split the array in form of rows
print(np.vsplit(arr3,2))

[[0 1 2]
 [3 4 5]]
[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]
[array([[0, 1, 2]]), array([[3, 4, 5]])]


Indexing using boolean Arrays:

In [62]:
arr = np.random.randint(1,100,24).reshape(6,4) # random numbers creation
print(arr)

[[63 69 56 91]
 [57 74 99 84]
 [78 79 40 54]
 [49 75 55  2]
 [ 1 88 86 87]
 [26 30 78 30]]


In [63]:
#boolean array
arr>50

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True,  True, False],
       [False,  True,  True,  True],
       [False, False,  True, False]])

In [64]:
#overlaping boolean array on real array
arr[arr>50]

array([63, 69, 56, 91, 57, 74, 99, 84, 78, 79, 54, 75, 55, 88, 86, 87, 78],
      dtype=int32)

In [65]:
arr[(arr>50)&(arr%2!=0)]

array([63, 69, 91, 57, 99, 79, 75, 55, 87], dtype=int32)

In [73]:
#set 0 on all these given condition numbers
arr[(arr>50) & (arr%2!=0)]=0

In [74]:
arr

array([[ 0,  0, 56,  0],
       [ 0, 74,  0, 84],
       [78,  0, 40, 54],
       [49,  0,  0,  2],
       [ 1, 88, 86,  0],
       [26, 30, 78, 30]], dtype=int32)

Broadcasting:

In [75]:
#Example:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(3).reshape(1,3)

print("Array 1:\n",arr1)
print("Array 2: ",arr2)

print("Broad casting:\n",arr1+arr2)

Array 1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Array 2:  [[0 1 2]]
Broad casting:
 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


Rules For Broadcasting:

In [78]:
# 1.if x=m &  y=n, operation will execute
a1 = np.arange(16).reshape(2,8)
a2 = np.arange(8,24).reshape(2,8)

print("a1 :\n",a1)
print("a2 :\n",a2)
print("Broadcasting :\n",a1+a2)

a1 :
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
a2 :
 [[ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
Broadcasting :
 [[ 8 10 12 14 16 18 20 22]
 [24 26 28 30 32 34 36 38]]


In [80]:
# 2. if x=1 & y=n then also operations will execute (same correspondance)
a3 = np.arange(4).reshape(1,4)
a4 = np.arange(12).reshape(3,4)

print("a3 :\n",a3)
print("a4 :\n",a4)

print("Broadcasting :\n",a3+a4)

a5 = np.arange(4).reshape(4,1)
a6 = np.arange(12).reshape(4,3)

print("a5 :\n",a5)
print("a6 :\n",a6)

print("Broadcasting :\n",a5+a6)

a3 :
 [[0 1 2 3]]
a4 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Broadcasting :
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
a5 :
 [[0]
 [1]
 [2]
 [3]]
a6 :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Broadcasting :
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [81]:
# 3. if x=1 & y!=n then operation will not execute
a7 = np.arange(3).reshape(1,3)
a8 = np.arange(16).reshape(4,4)

print("a7 :\n",a7)
print("a8 :\n",a8)
print("Broadcasting :\n",a7+a8)

a7 :
 [[0 1 2]]
a8 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [91]:
# 4. if (1,n) & (m ,1) then if will become (m,n) , operaiortn will execute
a9 = np.arange(4).reshape(1,4)
a10 = np.arange(4).reshape(4,1)

print("a9 :\n",a9)
print("a10 :\n",a10)
print("Broadcasting :\n",a9+a10)

a9 :
 [[0 1 2 3]]
a10 :
 [[0]
 [1]
 [2]
 [3]]
Broadcasting :
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [92]:
# 5.if x = 1 & y=1 , then operations will also executw
a11 = np.arange(1).reshape(1,1)
a12 = np.arange(16).reshape(4,4)

print("a11 :\n",a11)
print("a12 :\n",a12)

print("Broadcasting :\n",a11+a12)



a11 :
 [[0]]
a12 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Broadcasting :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [93]:
# 6. if they are of diffferent dimenstions 
a13 = np.arange(4)
a14 = np.arange(24).reshape(6,4)

print("a13 :\n",a13)
print("a14 :\n",a14)

print("broadcasting :\n",a13+a14)

a13 :
 [0 1 2 3]
a14 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
broadcasting :
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]
 [16 18 20 22]
 [20 22 24 26]]


handling Missing Values:

In [94]:
# missing values ----> nan
a = np.array([1,2,3,4,np.nan,5.6,np.nan])
print(a)

[1.  2.  3.  4.  nan 5.6 nan]
